server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/json
    min-response-size: 1024

spring:
  mvc:
    async:
      request-timeout: 600000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240MB
      max-request-size: 10240MB
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:file:./drive;DATABASE_TO_LOWER=TRUE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

storage:
  file-system:
    location: /home/jhonatapers/callv2/storage